# Generated by Django 5.1.3 on 2024-11-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_vector_path', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='university_vector_path',
        ),
    ]
