# Generated by Django 5.1.3 on 2024-12-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunt', '0002_university_remove_userprofile_university_vector_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='personality_vector_path',
            new_name='strongth',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mbti',
            field=models.CharField(blank=True, choices=[('INTJ', 'INTJ'), ('INTP', 'INTP'), ('ENTJ', 'ENTJ'), ('ENTP', 'ENTP'), ('INFJ', 'INFJ'), ('INFP', 'INFP'), ('ENFJ', 'ENFJ'), ('ENFP', 'ENFP'), ('ISTJ', 'ISTJ'), ('ISFJ', 'ISFJ'), ('ESTJ', 'ESTJ'), ('ESFJ', 'ESFJ'), ('ISTP', 'ISTP'), ('ISFP', 'ISFP'), ('ESTP', 'ESTP'), ('ESFP', 'ESFP')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subjects',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='want',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weekness',
            field=models.TextField(blank=True, null=True),
        ),
    ]
