# Generated by Django 5.1.3 on 2024-12-14 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunt', '0003_rename_personality_vector_path_userprofile_strongth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='strongth',
            new_name='strength',
        ),
    ]
