# Generated by Django 5.1.3 on 2024-12-14 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunt', '0004_rename_strongth_userprofile_strength'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='weekness',
            new_name='weskness',
        ),
    ]
