# Generated by Django 5.1.3 on 2024-12-14 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunt', '0005_rename_weekness_userprofile_weskness'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='weskness',
            new_name='weakness',
        ),
    ]
