# Generated by Django 5.1.3 on 2024-12-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunt', '0006_rename_weskness_userprofile_weakness'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='skill',
            field=models.TextField(blank=True, null=True),
        ),
    ]
