# Generated by Django 5.1.3 on 2025-01-02 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunt', '0007_userprofile_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatlog',
            name='university_vector_path',
        ),
        migrations.RemoveField(
            model_name='chatlog',
            name='user_vector_path',
        ),
    ]
