# Generated by Django 5.1.3 on 2025-01-02 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunt', '0008_remove_chatlog_university_vector_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatlog',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_logs', to='job_hunt.company'),
        ),
    ]
