# Generated by Django 5.1.3 on 2025-01-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunt', '0009_alter_chatlog_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='effort',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
