# Generated by Django 5.1.3 on 2025-01-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunt', '0010_userprofile_effort_userprofile_pr'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avoid',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='career',
            field=models.TextField(blank=True, null=True),
        ),
    ]
