# Generated by Django 5.1.3 on 2025-01-20 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunt', '0012_company_pr_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='strength',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='weakness',
        ),
    ]
