# Generated by Django 5.1.3 on 2025-01-20 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunt', '0013_remove_userprofile_strength_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatlog',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_logs', to='job_hunt.company'),
        ),
    ]
