# Generated by Django 5.1.3 on 2025-01-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunt', '0017_userprofile_effort_check_userprofile_pr_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='effort_check',
            field=models.TextField(blank=True, null=True),
        ),
    ]
